INSERT INTO RESTAURANTE("ID","NOME", "QTDE" ) values(1,'Bobs',0);
INSERT INTO RESTAURANTE("ID","NOME", "QTDE" ) values(2,'Burguer King',0);
INSERT INTO RESTAURANTE("ID","NOME", "QTDE" ) values(3,'Outback',0);
INSERT INTO RESTAURANTE("ID","NOME", "QTDE" ) values(4,'Pizza Hut',0);
INSERT INTO RESTAURANTE("ID","NOME", "QTDE" ) VALUES (5,'Mc Donalds',0)